### ISSUE TITLE
Default Project is set to FMod

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#15]
This contradicts the documentation that says that Audiere is the default audio source.

**Comment by SethRobinson** [comment]
Thanks.  Hmm, where does it say this?  I looked around and couldn't find it.  Not sure if you mean the codedojo page, config_template.txt or source code itself.

**Comment by Meerkov** [comment]
I think I actually read it in the "do these tutorials first" for proton.
https://www.rtsoft.com/wiki/doku.php?id=proton:win_setup2

So there might have been some confusion, since they both are made by you, I guess I thought that FMOD wouldn't be the default (I didn't see any setup instructions for getting FMOD, it doesn't seem to be free).

**Comment by SethRobinson** [comment]
Thanks, I've reworded it for the next commit:

_This project works similar to that, so it should be checked out as a Proton subfolder,
just like those examples.  You should probably change the release build (using the MSVS configuration manager) from FMOD_Release_GL to Release_GL so Audiere will be used instead of FMOD for the audio, that way you don't have to download FMOD lib stuff to get started._
