### ISSUE TITLE
rectangle memory

### ISSUE THREAD

**Issue by ninja-xyz** [SethRobinson/UGT#54]
It would be useful to be able to recall the penultimate rectangle drawn. Let me explain: sometimes it is necessary to translate the entire screen, but the command is interpreted as a new rectangle. In these cases it would be useful to recall the penultimate rectangle drawn, because it included a smaller area where the dialogues usually appear. This way you avoid having to redraw the rectangle to be able to retranslate only a small area where the dialogues appear.

**Comment by SethRobinson** [comment]
Hmmm.  I see what you mean... Currently I guess there are three hotkeys - one to translate a rect, one for the "active window", and one for the "whole desktop". 

The current system is kind of confusing because once setting the rect, "Active window" will use that rect instead of the "active window".   IIRC, If you use "whole desktop", it shouldn't affect the rect though, correct?  (I guess that would only be a work around if your game is full screen though)

Maybe I should just create a forth hotkey for "Last rect used" and have "active window" be its own thing that doesn't affect the rect. ?

**Comment by ninja-xyz** [comment]
"Active window" will use that rect instead of the "active window".

That's right, active window recalls the last rectangle drawn, even if you use borderless game to enlarge the window to full screen.
This means that to translate the entire active window, once you set a small rectangle for dialogs only, you must necessarily use the command to translate the entire desktop, and this overwrites the small rectangle previously drawn.

"Maybe I should just create a forth hotkey for "Last rect used" and have "active window" be its own thing that doesn't affect the rect. ?"

Yes this would be a good solution, because it avoids having to redraw new rectangles all the time. Useful with both mouse and keyboard, but especially with the joypad. : )

**Comment by SethRobinson** [comment]
Ok, it's been added!

**Comment by ninja-xyz** [comment]
tanx, when the next version will be ready?

Il giorno gio 6 lug 2023 alle ore 07:36 Seth Robinson <
***@***.***> ha scritto:

**Comment by SethRobinson** [comment]
The one with this rect improvement?  I released it three weeks ago!  If you run it, it should prompt you to update.  Or just click [here](https://www.rtsoft.com/files/UniversalGameTranslator_Windows.zip).

**Comment by ninja-xyz** [comment]
Ah ok tanx. In download. :)

Il giorno dom 30 lug 2023 alle ore 07:53 Seth Robinson <
***@***.***> ha scritto:
